# Generated by Django 3.1.2 on 2020-10-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_worker_booked_history'),
        ('workspace', '0003_auto_20201003_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='worker_n',
            field=models.ManyToManyField(to='worker.Worker'),
        ),
    ]
