# Generated by Django 3.1.2 on 2020-10-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_booked_worker_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='worker_n',
            new_name='worker_at',
        ),
    ]
