# Generated by Django 3.1.2 on 2020-10-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_auto_20201003_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='office',
            field=models.ManyToManyField(to='workspace.Office'),
        ),
        migrations.AddField(
            model_name='booked',
            name='room',
            field=models.ManyToManyField(to='workspace.Room'),
        ),
    ]
