# Generated by Django 3.1.2 on 2020-10-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_auto_20201003_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='office',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workspace.office'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(),
        ),
    ]
