# Generated by Django 3.1.2 on 2020-10-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_auto_20201003_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.office'),
        ),
    ]
