# Generated by Django 3.1.2 on 2020-10-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20201003_0936'),
        ('workspace', '0010_auto_20201003_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='office',
        ),
        migrations.AddField(
            model_name='booked',
            name='office',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workspace.office'),
        ),
        migrations.RemoveField(
            model_name='booked',
            name='room',
        ),
        migrations.AddField(
            model_name='booked',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='workspace.room'),
        ),
        migrations.AlterField(
            model_name='booked',
            name='time_from',
            field=models.IntegerField(choices=[(7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00')]),
        ),
        migrations.AlterField(
            model_name='booked',
            name='time_to',
            field=models.IntegerField(choices=[(7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00')]),
        ),
        migrations.RemoveField(
            model_name='booked',
            name='worker_at',
        ),
        migrations.AddField(
            model_name='booked',
            name='worker_at',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='worker.worker'),
        ),
    ]
