# Generated by Django 3.1.2 on 2020-10-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_auto_20201003_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='office',
        ),
    ]
