# Generated by Django 3.1.2 on 2020-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_auto_20201003_0922'),
        ('worker', '0002_worker_booked_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='booked_history',
            field=models.ManyToManyField(blank=True, to='workspace.Booked'),
        ),
    ]
